/**
 * Export Manager - Handle data export to files (Week 4)
 *
 * Supports:
 * - JSON export
 * - CSV export
 * - File download in browser
 */

import { ExperimentResults, ExportData, SimulationMetrics } from '../types/metrics';
import { MetricsAnalyzer } from '../systems/MetricsAnalyzer';

export class ExportManager {
  /**
   * Export single run as JSON
   */
  static exportRunJSON(metrics: SimulationMetrics): void {
    const filename = `run_${metrics.runId.substring(0, 8)}_${Date.now()}.json`;
    const json = JSON.stringify(metrics, null, 2);

    this.downloadFile(filename, json, 'application/json');
    console.log(`📥 Exported run to ${filename}`);
  }

  /**
   * Export experiment results as JSON
   */
  static exportExperimentJSON(results: ExperimentResults): void {
    const exportData: ExportData = {
      metadata: {
        exportedAt: Date.now(),
        version: '1.0.0',
        projectName: 'Maze Mind'
      },
      experiment: results
    };

    const filename = `experiment_${results.config.name}_${Date.now()}.json`;
    const json = JSON.stringify(exportData, null, 2);

    this.downloadFile(filename, json, 'application/json');
    console.log(`📥 Exported experiment to ${filename}`);
  }

  /**
   * Export experiment results as CSV
   */
  static exportExperimentCSV(results: ExperimentResults): void {
    const csv = MetricsAnalyzer.generateCSV(results);
    const filename = `experiment_${results.config.name}_${Date.now()}.csv`;

    this.downloadFile(filename, csv, 'text/csv');
    console.log(`📥 Exported experiment to ${filename}`);
  }

  /**
   * Export current agent memory stream
   */
  static exportMemories(memories: any[]): void {
    const filename = `memories_${Date.now()}.json`;
    const json = JSON.stringify(memories, null, 2);

    this.downloadFile(filename, json, 'application/json');
    console.log(`📥 Exported ${memories.length} memories to ${filename}`);
  }

  /**
   * Download file to browser
   */
  private static downloadFile(filename: string, content: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';

    document.body.appendChild(link);
    link.click();

    // Cleanup
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 100);
  }

  /**
   * Generate summary report as text
   */
  static generateSummaryReport(results: ExperimentResults): string {
    const stats = results.stats;

    const report = `
MAZE MIND EXPERIMENT SUMMARY
============================

Experiment: ${results.config.name}
Date: ${new Date(results.startTime).toLocaleString()}
Duration: ${results.totalDuration.toFixed(1)}s

CONFIGURATION
-------------
Runs: ${results.config.numberOfRuns}
Maze Size: ${results.config.mazeWidth}x${results.config.mazeHeight}
Time Scale: ${results.config.timeScale}x
LLM Provider: ${results.config.llmProvider}

RESULTS
-------
Total Runs: ${stats.totalRuns}
Success Rate: ${(stats.successRate * 100).toFixed(1)}%
Successes: ${stats.successCount}

OUTCOMES
--------
Deaths (Starvation): ${stats.deathByStarvation}
Deaths (Dehydration): ${stats.deathByDehydration}
Deaths (Exhaustion): ${stats.deathByExhaustion}
Mental Breakdowns: ${stats.mentalBreakdowns}
Timeouts: ${stats.timeouts}

SURVIVAL METRICS
----------------
Avg Survival Time: ${this.formatTime(stats.avgSurvivalTime)}
Min Survival Time: ${this.formatTime(stats.minSurvivalTime)}
Max Survival Time: ${this.formatTime(stats.maxSurvivalTime)}
Std Deviation: ${stats.stdDevSurvivalTime.toFixed(1)}s

RESOURCE METRICS
----------------
Avg Final Stress: ${stats.avgFinalStress.toFixed(1)}%
Avg Items Consumed: ${stats.avgItemsConsumed.toFixed(1)}
Avg Exploration: ${(stats.avgExplorationProgress * 100).toFixed(1)}%

${stats.avgTimeToExit ? `
SUCCESS METRICS (${stats.successCount} runs)
--------------------
Avg Time to Exit: ${this.formatTime(stats.avgTimeToExit)}
Avg Efficiency: ${((stats.avgEfficiency || 0) * 100).toFixed(1)}%
` : ''}

Generated by Maze Mind v1.0
    `.trim();

    return report;
  }

  /**
   * Export summary report as text file
   */
  static exportSummaryReport(results: ExperimentResults): void {
    const report = this.generateSummaryReport(results);
    const filename = `summary_${results.config.name}_${Date.now()}.txt`;

    this.downloadFile(filename, report, 'text/plain');
    console.log(`📥 Exported summary to ${filename}`);
  }

  /**
   * Format time in MM:SS
   */
  private static formatTime(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }
}
